USE Metro
GO

ALTER TABLE LinkerT
	ADD FOREIGN KEY (LineID) 
	REFERENCES TrainsT (LineID)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

ALTER TABLE LinkerT
	ADD FOREIGN KEY (Line) 
	REFERENCES LinesT (Line)
	ON DELETE CASCADE
	ON UPDATE CASCADE;

